### ISSUE TITLE
GCC Warnings

### ISSUE THREAD

**Issue by nogweii** [Kiwi/clyde#40]
Just thought I'd bring them to your attention. Just now, pulled the PKGBUILD for clyde-git from AUR; got these following warnings.

```
clydelib/lsignal.c: In function 'sighook':
clydelib/lsignal.c:167: warning: unused parameter 'ar'
clydelib/lsignal.c: In function 'l_signal':
clydelib/lsignal.c:231: warning: 'sig' may be used uninitialized in this function
```

Have a nice day?

PS: Have you guys ran valgrind on clydelib/ yet? It could provide some interesting bugs you haven't noticed (normally, memory leaks). Also, lint, which is a C/C++ quality checker. Not that important, but code is art! And ugly art is, well, ugly.

**Comment by Kiwi** [comment]
Not a bug.

**Comment by dropwhile** [comment]
These are both just gcc compile warnings.
The first one is pretty dumb. Just gcc saying that a parameter isn't used in the function. This parameter is required due to callback requirements for lua (kind of like an interface).

The second one is just a warning that sig may be unused. This could happen if certain logic branches are chosen, resulting in sig not having a value. Easy fix.

Patch to resolve both warnings: http://gist.github.com/377529

**Comment by nogweii** [comment]
cactus is awesome.
