### ISSUE TITLE
ReposOnly fails

### ISSUE THREAD

**Issue by dcampbell24** [Kiwi/clyde#53]
After enabling ReposOnly, clyde still tries to download from the AUR.

**Comment by Kiwi** [comment]
ReposOnly only affects searching.

**Comment by dcampbell24** [comment]
How does clyde find a package to install without searching for it? (I know what you mean, but think about it. The meaning of the comment for this option is not exactly clear.)

Also, maybe ReposOnly should apply to everything. Why would someone want to exclude the AUR only when using search? If someone is not searching for packages from the AUR, he probably does not want to install packages from the AUR. If he wanted to make an exception for something, --aur could be there for him.

**Comment by Kiwi** [comment]
The correct way to install something from aur when it exists there and in repos would be with clyde -S aur/package. That is currently not implemented yet. >.> As it is now it will always pick from repos a package by same name.

It was added because some people do not want the hundreds of extra aur results all the time and only wanted it when you had --aur. It is not meant to be anything more than a convenience for searching. See above for why there is no need for an exception.
