### ISSUE TITLE
Can't build from AUR after ctrl + | terminationg

### ISSUE THREAD

**Issue by AphonicChaos** [Kiwi/clyde#6]
Steps to reproduce:
1. Run any clyde command: clyde freecol
2. Press Ctrl + | to terminate (because Ctrl + C doesn't work)
3. Run another clyde command, trying to install from aur: clyde freecol, etc

Expected Outcome:
freecol (or any) PKGBUILD should be downloaded and installed

Actual Outcome:
clyde freecol
1 aur/freecol 0.9.1-1 (160)
    A turn-based strategy game based on Colonization
2 aur/freecolor 0.8.8-1 (5)
    Displays free memory as a bargraph on the command line.
==>  Enter #'s (separated by blanks) of packages to be installed
==>  ------------------------------------------------------------
==> 1
:: freecol package not found, searching for group...
:: freecol group not found, searching AUR...

==> Installing the following packages from AUR
Targets (2): freecol  java-runtime  

==> Proceed with installation? [Y/n] y
==> Downloading java-runtime.tar.gz

bsdtar: Unrecognized archive format  
bsdtar: Error exit delayed from previous errors.  
    ( Unsupported package from AUR: Potentially dangerous! )  
==> Edit the PKGBUILD (highly recommended for security reasons)? [Y/n] n
==> ERROR: PKGBUILD does not exist.
Build failed

Steps taken to correct:
deleted /tmp/clyde
uninstalled and reinstalled clyde

**Comment by Kiwi** [comment]
This probably has nothing to do with ctrl+| and is instead because for whatever reason it is not figuring out that java-runtime is provided by openjdk6/jre. The only reason I could see the ctrl+| actually doing it is if you somehow screwed up your database. :/ If it is not finding any packages in repos that it should then maybe you did do that...

[kiwi@lappy:lua/clyde]$ clyde -Ss java-runtime        (03-06 15:56)

extra/openjdk6 6.b17_1.7.1-1 [42.84 MB]
Free Java environment based on OpenJDK 6.0 with IcedTea6 replacing binary plugs.
community/jre 6u18-1 [32.79 MB]
Sun's java runtime environment
[kiwi@lappy:lua/clyde]$

**Comment by AphonicChaos** [comment]
Yep. worked fine after I installed a java-runtime first as suggested. Yaourt seems to be able to handle provides and so does Bauerbill (still waiting on that cage match), so perhaps this is still a valid bug?

**Comment by Kiwi** [comment]
Closing due to there being a duplicate issue now describing the actual problem.
