### ISSUE TITLE
Reparse PKGBUILD so that name changes can work (among other things I am sure)

### ISSUE THREAD

**Issue by Kiwi** [Kiwi/clyde#70]
< bug2000> When I try to build a package from AUR, and change it's package name in the package build [Because I want the repo's to overwrite it when it gets updated], it doesn't install it.

**Comment by sebnow** [comment]
Looks like this would require quite a large rewrite of aur_install(). Currently the packages are downloaded and extracted one-by-one. Customization is done at the same time. In order to correctly handle renaming packages the whole process (checking pacman deps, provides, reverse depends, etc) would need to be "restarted".

I think in order to simplify the process, and possibly provide a better user experience, the PKGBUILD download and customization process would need to be done in one batch, before the build process is started (i.e. download, extract, customize, loop through each package to build & install). Of course if the package is renamed, the whole customization process needs to be rerun as well (package A depends on package B, package B is renamed to C -> package A needs to be updated), so it could take a few cycles before everything is actually properly customized. Alternatively clyde would need the smarts to know about the rename and just substitute the old name for the new name in all the depends/provides/replaces/conflicts.
