### ISSUE TITLE
Aborts whenever an unexpected callback type is received

### ISSUE THREAD

**Issue by schuay** [Kiwi/clyde#77]
Clyde errors out whenever an unhandled callback type is received (for example, see http://github.com/Kiwi/clyde/blob/master//lualpm.c#L2032 ).

This means that clyde could be broken by every new pacman release. In a bad (but still very possible) scenario, this would mean clyde would not even be able to update itself.

It's not a good idea to abort in this situation. alpm is coded in such a way that not handling a callback (at least pmtransevt/pmtranconv) will fall back to a sane default behavior.

**Comment by juster** [comment]
Clyde will also be broken by a new pacman release because the API for pacman changes. Functions that were used go missing or get renamed. The version of the dynamic library for libalpm that clyde links to is also deleted, so a link error occurs and clyde cannot start. This happened when pacman went from 3.3.x to 3.4.

I would prefer that clyde throw a lua error with a better error message. However I think stopping completely is the right action because we want to handle all types of errors. If we miss one it is basically a bug...

**Comment by schuay** [comment]
I actually came across this issue while working on a pacman patch. This patch adds 2 new members to pmtransconv_t and 1 new member to pmtransevt_t. The function signatures themselves remain unchanged.

Clyde reaches the new events every time it tries to update / install something from the AUR and aborts. There would be no harm done if these members were not handled, because they fall back to sane defaults. The way it's implemented currently would force all clyde users to manually wget && makepkg clyde (once it is updated) to get a working version.

I agree clyde shouldn't ignore something like this, but I think it would be better to print a warning and then continue executing rather than aborting.

**Comment by schuay** [comment]
I guess what I'm saying is that possibly breaking clyde would be better than definitely breaking clyde :)

**Comment by juster** [comment]
Oops I kind of forgot about this. I will reopen this and try to fix this once I re-organize transaction callbacks. I have been rewriting some callback code lately to try to add a patch for the fetch callback.

**Comment by juster** [comment]
This should be fixed now as of version 0.03.06.
